helpers do 

	def blue_line
		blue_line = {}
		
		blue_line["30172"] = "O'Hare Airport (Forest Pk-bound)"
		blue_line["30171"] = "O'Hare Airport (Terminal Arrival)"
		blue_line["30160"] = "Rosemont (Forest Pk-bound)"
		blue_line["30159"] = "Rosemont (O'Hare-bound)"
		blue_line["30045"] = "Cumberland (Forest Pk-bound)"
		blue_line["30044"] = "Cumberland (O'Hare-bound)"
		blue_line["30146"] = "Harlem (O'Hare Branch) (Forest Pk-bound)"
		blue_line["30145"] = "Harlem (O'Hare Branch) (O'Hare-bound)"
		blue_line["30248"] = "Jefferson Park (Forest Pk-bound)"
		blue_line["30247"] = "Jefferson Park (O'Hare-bound)"
		blue_line["30260"] = "Montrose (Forest Pk-bound)"
		blue_line["30259"] = "Montrose (O'Hare-bound)"
		blue_line["30108"] = "Irving Park (O'Hare Branch) (Forest Pk-bound)"
		blue_line["30107"] = "Irving Park (O'Hare Branch) (O'Hare-bound)"
		blue_line["30240"] = "Addison (O'Hare Branch) (Forest Pk-bound)"
		blue_line["30239"] = "Addison (O'Hare Branch) (O'Hare-bound)"
		blue_line["30013"] = "Belmont (O'Hare Branch) (Forest Pk-bound)"
		blue_line["30012"] = "Belmont (O'Hare Branch) (O'Hare-bound)"
		blue_line["30198"] = "Logan Square (Forest Pk-bound)"
		blue_line["30197"] = "Logan Square (O'Hare-bound)"
		blue_line["30112"] = "California/Milwaukee (Forest Pk-bound)"
		blue_line["30111"] = "California/Milwaukee (O'Hare-bound)"
		blue_line["30130"] = "Western/Milwaukee (Forest Pk-bound)"
		blue_line["30129"] = "Western/Milwaukee (O'Hare-bound)"
		blue_line["30116"] = "Damen/Milwaukee (Forest Pk-bound)"
		blue_line["30115"] = "Damen/Milwaukee (O'Hare-bound)"
		blue_line["30063"] = "Division/Milwaukee (Forest Pk-bound)"
		blue_line["30062"] = "Division/Milwaukee (O'Hare-bound)"
		blue_line["30272"] = "Chicago/Milwaukee (Forest Pk-bound)"
		blue_line["30271"] = "Chicago/Milwaukee (O'Hare-bound)"
		blue_line["30096"] = "Grand/Milwaukee (Forest Pk-bound)"
		blue_line["30095"] = "Grand/Milwaukee (O'Hare-bound)"
		blue_line["30374"] = "Clark/Lake (Forest Pk-bound)"
		blue_line["30375"] = "Clark/Lake (O'Hare-bound)"
		blue_line["30073"] = "Washington/Dearborn (Forest Pk-bound)"
		blue_line["30072"] = "Washington/Dearborn (O'Hare-bound)"
		blue_line["30154"] = "Monroe/Dearborn (Forest Pk-bound)"
		blue_line["30153"] = "Monroe/Dearborn (O'Hare-bound)"
		blue_line["30015"] = "Jackson/Dearborn (Forest Pk-bound)"
		blue_line["30014"] = "Jackson/Dearborn (O'Hare-bound)"
		blue_line["30262"] = "LaSalle (Forest Pk-bound)"
		blue_line["30261"] = "LaSalle (O'Hare-bound)"
		blue_line["30085"] = "Clinton (Forest Pk-bound)"
		blue_line["30084"] = "Clinton (O'Hare-bound)"
		blue_line["30069"] = "UIC-Halsted (Forest Pk-bound)"
		blue_line["30068"] = "UIC-Halsted (O'Hare-bound)"
		blue_line["30093"] = "Racine (Forest Pk-bound)"
		blue_line["30092"] = "Racine (O'Hare-bound)"
		blue_line["30158"] = "Illinois Medical District (Forest Pk-bound)"
		blue_line["30157"] = "Illinois Medical District (O'Hare-bound)"
		blue_line["30043"] = "Western (Forest Pk-bound)"
		blue_line["30042"] = "Western (O'Hare-bound)"
		blue_line["30049"] = "Kedzie-Homan (Forest Pk-bound)"
		blue_line["30048"] = "Kedzie-Homan (O'Hare-bound)"
		blue_line["30180"] = "Pulaski (Forest Pk-bound)"
		blue_line["30179"] = "Pulaski (O'Hare-bound)"
		blue_line["30188"] = "Cicero (Forest Pk-bound)"
		blue_line["30187"] = "Cicero (O'Hare-bound)"
		blue_line["30002"] = "Austin (Forest Pk-bound)"
		blue_line["30001"] = "Austin (O'Hare-bound)"
		blue_line["30035"] = "Oak Park (Forest Pk-bound)"
		blue_line["30034"] = "Oak Park (O'Hare-bound)"
		blue_line["30190"] = "Harlem (Forest Pk-bound)"
		blue_line["30189"] = "Harlem (O'Hare-bound)"
		blue_line["30076"] = "Forest Park (O'Hare-bound)"
		blue_line["30077"] = "Forest Park (Terminal Arrival)"
		
		return blue_line


	end

end