module BrownLineHelper
	def brown_line
		brown_line ={}

		brown_line["30250"]	= "Kimball (Loop-bound)"
		brown_line["30249"]	= "Kimball (Terminal arrival)"
		brown_line["30225"]	= "Kedzie (Kimball-bound)"
		brown_line["30226"]	= "Kedzie (Loop-bound)"
		brown_line["30167"]	= "Francisco (Kimball-bound)"
		brown_line["30168"]	= "Francisco (Loop-bound)"
		brown_line["30195"]	= "Rockwell (Kimball-bound)"
		brown_line["30196"]	= "Rockwell (Loop-bound)"
		brown_line["30283"]	= "Western (Kimball-bound)"
		brown_line["30284"]	= "Western (Loop-bound)"
		brown_line["30018"]	= "Damen (Kimball-bound)"
		brown_line["30019"]	= "Damen (Loop-bound)"
		brown_line["30287"]	= "Montrose (Kimball-bound)"
		brown_line["30288"]	= "Montrose (Loop-bound)"
		brown_line["30281"]	= "Irving Park (Kimball-bound)"
		brown_line["30282"]	= "Irving Park (Loop-bound)"
		brown_line["30277"]	= "Addison (Kimball-bound)"
		brown_line["30278"]	= "Addison (Loop-bound)"
		brown_line["30253"]	= "Paulina (Kimball-bound)"
		brown_line["30254"]	= "Paulina (Loop-bound)"
		brown_line["30070"]	= "Southport (Kimball-bound)"
		brown_line["30071"]	= "Southport (Loop-bound)"
		brown_line["30257"]	= "Belmont (Kimball-Linden-bound)"
		brown_line["30258"]	= "Belmont (Loop-bound)"
		brown_line["30231"]	= "Wellington (Kimball-Linden-bound)"
		brown_line["30232"]	= "Wellington (Loop-bound)"
		brown_line["30103"]	= "Diversey (Kimball-Linden-bound)"
		brown_line["30104"]	= "Diversey (Loop-bound)"
		brown_line["30235"]	= "Fullerton (Kimball-Linden-bound)"
		brown_line["30236"]	= "Fullerton (Loop-bound)"
		brown_line["30127"]	= "Armitage (Kimball-Linden-bound)"
		brown_line["30128"]	= "Armitage (Loop-bound)"
		brown_line["30155"]	= "Sedgwick (Kimball-Linden-bound)"
		brown_line["30156"]	= "Sedgwick (Loop-bound)"
		brown_line["30137"]	= "Chicago/Franklin (Kimball-Linden-bound)"
		brown_line["30138"]	= "Chicago/Franklin (Loop-bound)"
		brown_line["30090"]	= "Merchandise Mart (Kimball-Linden-bound)"
		brown_line["30091"]	= "Merchandise Mart (Loop-bound)"
		brown_line["30142"]	= "Washington/Wells (Outer Loop)"
		brown_line["30008"]	= "Quincy/Wells (Outer Loop)"
		brown_line["30030"]	= "LaSalle/Van Buren (Outer Loop)"
		brown_line["30165"]	= "Library (Outer Loop)"
		brown_line["30131"]	= "Adams/Wabash (Outer Loop)"
		brown_line["30123"]	= "Madison/Wabash (Outer Loop)"
		brown_line["30038"]	= "Randolph/Wabash (Outer Loop)"
		brown_line["30051"]	= "State/Lake (Outer Loop)"
		brown_line["30075"]	= "Clark/Lake (Outer Loop)"

		return brown_line
	end
end
