helpers do
	def purple_line_exp
		purple_line_exp = {}

		purple_line_exp["30204"] = "Linden (Howard-Loop-bound)"
		purple_line_exp["30203"] = "Linden (Linden-bound)"
		purple_line_exp["30242"] = "Central-Evanston (Howard-Loop-bound)"
		purple_line_exp["30241"] = "Central-Evanston (Linden-bound)"
		purple_line_exp["30079"] = "Noyes (Howard-Loop-bound)"
		purple_line_exp["30078"] = "Noyes (Linden-bound)"
		purple_line_exp["30102"] = "Foster (Howard-Loop-bound)"
		purple_line_exp["30101"] = "Foster (Linden-bound)"
		purple_line_exp["30011"] = "Davis (Howard-Loop-bound)"
		purple_line_exp["30010"] = "Davis (Linden-bound)"
		purple_line_exp["30134"] = "Dempster (Howard-Loop-bound)"
		purple_line_exp["30133"] = "Dempster (Linden-bound)"
		purple_line_exp["30053"] = "Main (Howard-Loop-bound)"
		purple_line_exp["30052"] = "Main (Linden-bound)"
		purple_line_exp["30164"] = "South Blvd (Howard-Loop-bound)"
		purple_line_exp["30163"] = "South Blvd (Linden-bound)"
		purple_line_exp["30175"] = "Howard (NB) (Linden, Skokie-bound)"
		purple_line_exp["30176"] = "Howard (Terminal arrival)"
		purple_line_exp["30257"] = "Belmont (Kimball-Linden-bound)"
		purple_line_exp["30258"] = "Belmont (Loop-bound)"
		purple_line_exp["30231"] = "Wellington (Kimball-Linden-bound)"
		purple_line_exp["30232"] = "Wellington (Loop-bound)"
		purple_line_exp["30103"] = "Diversey (Kimball-Linden-bound)"
		purple_line_exp["30104"] = "Diversey (Loop-bound)"
		purple_line_exp["30235"] = "Fullerton (Kimball-Linden-bound)"
		purple_line_exp["30236"] = "Fullerton (Loop-bound)"
		purple_line_exp["30127"] = "Armitage (Kimball-Linden-bound)"
		purple_line_exp["30128"] = "Armitage (Loop-bound)"
		purple_line_exp["30155"] = "Sedgwick (Kimball-Linden-bound)"
		purple_line_exp["30156"] = "Sedgwick (Loop-bound)"
		purple_line_exp["30137"] = "Chicago/Franklin (Kimball-Linden-bound)"
		purple_line_exp["30138"] = "Chicago/Franklin (Loop-bound)"
		purple_line_exp["30090"] = "Merchandise Mart (Kimball-Linden-bound)"
		purple_line_exp["30091"] = "Merchandise Mart (Loop-bound)"
		purple_line_exp["30074"] = "Clark/Lake (Inner Loop)"
		purple_line_exp["30050"] = "State/Lake (Inner Loop)"
		purple_line_exp["30039"] = "Randolph/Wabash (Inner Loop)"
		purple_line_exp["30124"] = "Madison/Wabash (Inner Loop)"
		purple_line_exp["30132"] = "Adams/Wabash (Inner Loop)"
		purple_line_exp["30166"] = "Library (Inner Loop)"
		purple_line_exp["30031"] = "LaSalle/Van Buren (Inner Loop)"
		purple_line_exp["30007"] = "Quincy/Wells (Inner Loop)"
		purple_line_exp["30141"] = "Washington/Wells (Inner Loop)"

		return purple_line_exp
	end
end
