class SessionController < ApplicationController

	skip_before_filter :verify_authenticity_token

	def notice
	end

  def index
    redirect_to user_path(User.find(session[:user_id])) if session[:user_id] != nil
  end

  def first
  end

  def login
    @user = get_user(params[:user])
    
    if Time.now - @user.created_at < 2 #new users have pin autogenerated
      pin = rand.to_s.reverse
      pin = pin[0..3]
      @user.password_digest = pin
      @user.save!
      session[:user_id] = @user.id
      redirect_to user_path(User.find(session[:user_id])) if session[:user_id] != nil
    else
      flash[:notice] = "Phone number must be unique"
      redirect_to root_psath
    end
  end



  protected

  def get_user(user_params)
    User.find_or_create_by(phone: user_params[:phone])
  end
	
end
